/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package opera.view.PaineisDeCadastro;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author Luciano
 */
public class PnlCadastrarEquipamento_Geral extends javax.swing.JPanel {
    
    
    /**
     * Getters
     */
    public JButton getBtnCancelar(){
        return btnCancelar;
    }
    public JButton getBtnCadastrar(){
        return btnCadastrar;
    }

    public JPanel getPnlNovoEquipamento() {
        return pnlNovoEquipamento;
    }
    
    
    
    public JTextField getTxtDescricao(){
        return txtDescricao;
    }
    public JTextField getTxtNome(){
        return txtNome;
    }
    public JTextField getTxtPreco(){
        return txtPreco;
    }
        
    public JRadioButton getRdbArma(){
        return rdbArma;
    }
    public JRadioButton getRdbArmadura(){
        return rdbArmadura;
    }
    public JRadioButton getRdbItem() {
        return rdbItem;
    }
    
    public JTextField getTxtCusto(){
        return txtPreco;
    }
        
    public JTextField getTxtDestreza(){
        return txtDestreza;
    }
    public JTextField getTxtFisico(){
        return txtFisico;
    }
    public JTextField getTxtInteligencia(){
        return txtInteligencia;
    }
    public JTextField getTxtMana(){
        return txtMana;
    }
    public JTextField getTxtMente(){
        return txtMente;
    }
    public JTextField getTxtPercepcao(){
        return txtPercepcao;
    }
    public JTextField getTxtSorte(){
        return txtSorte;
    }
    public JTextField getTxtVontade(){
        return txtVontade;
    }
    
    public JCheckBox getChkDestreza(){
        return chkDestreza;
    }
    public JCheckBox getChkFisico(){
        return chkFisico;
    }
    public JCheckBox getChkInteligencia(){
        return chkInteligencia;
    }
    public JCheckBox getChkMana(){
        return chkMana;
    }
    public JCheckBox getChkMente(){
        return chkMente;
    }
    public JCheckBox getChkPercepcao(){
        return chkPercepcao;
    }
    public JCheckBox getChkSorte(){
        return chkSorte;
    }
    public JCheckBox getChkVontade(){
        return chkVontade;
    }

    public void setChkDestreza(JCheckBox chkDestreza) {
        this.chkDestreza = chkDestreza;
    }

    public void setChkFisico(JCheckBox chkFisico) {
        this.chkFisico = chkFisico;
    }

    public void setChkInteligencia(JCheckBox chkInteligencia) {
        this.chkInteligencia = chkInteligencia;
    }

    public void setChkMana(JCheckBox chkMana) {
        this.chkMana = chkMana;
    }

    public void setChkMente(JCheckBox chkMente) {
        this.chkMente = chkMente;
    }

    public void setChkPercepcao(JCheckBox chkPercepcao) {
        this.chkPercepcao = chkPercepcao;
    }

    public void setChkSorte(JCheckBox chkSorte) {
        this.chkSorte = chkSorte;
    }

    public void setChkVontade(JCheckBox chkVontade) {
        this.chkVontade = chkVontade;
    }

    public void setRdbArma(JRadioButton rdbArma) {
        this.rdbArma = rdbArma;
    }

    public void setRdbArmadura(JRadioButton rdbArmadura) {
        this.rdbArmadura = rdbArmadura;
    }

    public void setTxtDescricao(JTextField txtDescricao) {
        this.txtDescricao = txtDescricao;
    }

    public void setTxtDestreza(JTextField txtDestreza) {
        this.txtDestreza = txtDestreza;
    }

    public void setTxtFisico(JTextField txtFisico) {
        this.txtFisico = txtFisico;
    }

    public void setTxtInteligencia(JTextField txtInteligencia) {
        this.txtInteligencia = txtInteligencia;
    }

    public void setTxtMana(JTextField txtMana) {
        this.txtMana = txtMana;
    }

    public void setTxtMente(JTextField txtMente) {
        this.txtMente = txtMente;
    }

    public void setTxtNome(JTextField txtNome) {
        this.txtNome = txtNome;
    }

    public void setTxtPercepcao(JTextField txtPercepcao) {
        this.txtPercepcao = txtPercepcao;
    }

    public void setTxtPreco(JTextField txtPreco) {
        this.txtPreco = txtPreco;
    }

    public void setTxtSorte(JTextField txtSorte) {
        this.txtSorte = txtSorte;
    }

    public void setTxtVontade(JTextField txtVontade) {
        this.txtVontade = txtVontade;
    }
    
    
    

    /**
     * Creates new form PnlCadastrarEquipamento_Geral
     */
    public PnlCadastrarEquipamento_Geral() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpTipoEquipamento = new javax.swing.ButtonGroup();
        pnlNovoEquipamento = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        lblPreco = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        rdbArmadura = new javax.swing.JRadioButton();
        rdbArma = new javax.swing.JRadioButton();
        rdbItem = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        chkFisico = new javax.swing.JCheckBox();
        chkDestreza = new javax.swing.JCheckBox();
        chkInteligencia = new javax.swing.JCheckBox();
        chkVontade = new javax.swing.JCheckBox();
        txtInteligencia = new javax.swing.JTextField();
        txtVontade = new javax.swing.JTextField();
        txtDestreza = new javax.swing.JTextField();
        txtFisico = new javax.swing.JTextField();
        chkPercepcao = new javax.swing.JCheckBox();
        chkMente = new javax.swing.JCheckBox();
        chkMana = new javax.swing.JCheckBox();
        chkSorte = new javax.swing.JCheckBox();
        txtPercepcao = new javax.swing.JTextField();
        txtMente = new javax.swing.JTextField();
        txtMana = new javax.swing.JTextField();
        txtSorte = new javax.swing.JTextField();

        pnlNovoEquipamento.setBorder(javax.swing.BorderFactory.createTitledBorder("Novo Equipamento"));

        lblNome.setText("Nome:");

        lblDescricao.setText("Descricao:");

        lblPreco.setText("Preco:");

        javax.swing.GroupLayout pnlNovoEquipamentoLayout = new javax.swing.GroupLayout(pnlNovoEquipamento);
        pnlNovoEquipamento.setLayout(pnlNovoEquipamentoLayout);
        pnlNovoEquipamentoLayout.setHorizontalGroup(
            pnlNovoEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNovoEquipamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNovoEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescricao)
                    .addComponent(lblNome)
                    .addComponent(lblPreco))
                .addGap(50, 50, 50)
                .addGroup(pnlNovoEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNovoEquipamentoLayout.createSequentialGroup()
                        .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                    .addComponent(txtNome))
                .addContainerGap())
        );
        pnlNovoEquipamentoLayout.setVerticalGroup(
            pnlNovoEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNovoEquipamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNovoEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlNovoEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescricao)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlNovoEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPreco)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCancelar.setText("Cancelar");

        btnCadastrar.setText("Prosseguir/Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Equipamento"));

        grpTipoEquipamento.add(rdbArmadura);
        rdbArmadura.setSelected(true);
        rdbArmadura.setText("Armadura");

        grpTipoEquipamento.add(rdbArma);
        rdbArma.setText("Arma");

        grpTipoEquipamento.add(rdbItem);
        rdbItem.setText("Item");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdbArmadura)
                .addGap(18, 18, 18)
                .addComponent(rdbArma)
                .addGap(18, 18, 18)
                .addComponent(rdbItem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbArmadura)
                    .addComponent(rdbArma)
                    .addComponent(rdbItem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Bonus de Atributo"));

        chkFisico.setText("Fisico:");
        chkFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkFisicoActionPerformed(evt);
            }
        });

        chkDestreza.setText("Destreza:");
        chkDestreza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDestrezaActionPerformed(evt);
            }
        });

        chkInteligencia.setText("Inteligencia:");
        chkInteligencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkInteligenciaActionPerformed(evt);
            }
        });

        chkVontade.setText("Vontade:");
        chkVontade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkVontadeActionPerformed(evt);
            }
        });

        txtInteligencia.setEditable(false);

        txtVontade.setEditable(false);

        txtDestreza.setEditable(false);

        txtFisico.setEditable(false);

        chkPercepcao.setText("Percepcao:");
        chkPercepcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPercepcaoActionPerformed(evt);
            }
        });

        chkMente.setText("Mente:");
        chkMente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMenteActionPerformed(evt);
            }
        });

        chkMana.setText("Mana:");
        chkMana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkManaActionPerformed(evt);
            }
        });

        chkSorte.setText("Sorte:");
        chkSorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSorteActionPerformed(evt);
            }
        });

        txtPercepcao.setEditable(false);

        txtMente.setEditable(false);

        txtMana.setEditable(false);

        txtSorte.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkInteligencia)
                    .addComponent(chkVontade)
                    .addComponent(chkDestreza)
                    .addComponent(chkFisico))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chkPercepcao))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDestreza, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(txtVontade)
                            .addComponent(txtInteligencia))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkMente)
                            .addComponent(chkMana)
                            .addComponent(chkSorte))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPercepcao, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(txtSorte)
                    .addComponent(txtMana)
                    .addComponent(txtMente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkFisico)
                    .addComponent(txtFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkPercepcao)
                    .addComponent(txtPercepcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkDestreza)
                    .addComponent(txtDestreza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkMente)
                    .addComponent(txtMente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkInteligencia)
                    .addComponent(txtInteligencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkMana)
                    .addComponent(txtMana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkVontade)
                    .addComponent(txtVontade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkSorte)
                    .addComponent(txtSorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlNovoEquipamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlNovoEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnCadastrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chkFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkFisicoActionPerformed
        // TODO add your handling code here:
        if(chkFisico.isSelected()){
            getTxtFisico().setEditable(true);
        }
        else{
            getTxtFisico().setText("");
            getTxtFisico().setEditable(false);
        }
    }//GEN-LAST:event_chkFisicoActionPerformed

    private void chkDestrezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDestrezaActionPerformed
        // TODO add your handling code here:
        if(chkDestreza.isSelected()){
            getTxtDestreza().setEditable(true);
        }
        else{
            getTxtDestreza().setText("");
            getTxtDestreza().setEditable(false);
        }
    }//GEN-LAST:event_chkDestrezaActionPerformed

    private void chkInteligenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkInteligenciaActionPerformed
        // TODO add your handling code here:
        if(chkInteligencia.isSelected()){
            getTxtInteligencia().setEditable(true);
        }
        else{
            getTxtInteligencia().setText("");
            getTxtInteligencia().setEditable(false);
        }
    }//GEN-LAST:event_chkInteligenciaActionPerformed

    private void chkVontadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkVontadeActionPerformed
        // TODO add your handling code here:
        if(chkVontade.isSelected()){
            getTxtVontade().setEditable(true);
        }
        else{
            getTxtVontade().setText("");
            getTxtVontade().setEditable(false);
        }
    }//GEN-LAST:event_chkVontadeActionPerformed

    private void chkPercepcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPercepcaoActionPerformed
        // TODO add your handling code here:
        if(chkPercepcao.isSelected()){
            getTxtPercepcao().setEditable(true);
        }
        else{
            getTxtPercepcao().setText("");
            getTxtPercepcao().setEditable(false);
        }
    }//GEN-LAST:event_chkPercepcaoActionPerformed

    private void chkMenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMenteActionPerformed
        // TODO add your handling code here:
        if(chkMente.isSelected()){
            getTxtMente().setEditable(true);
        }
        else{
            getTxtMente().setText("");
            getTxtMente().setEditable(false);
        }
    }//GEN-LAST:event_chkMenteActionPerformed

    private void chkManaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkManaActionPerformed
        // TODO add your handling code here:
        if(chkMana.isSelected()){
            getTxtMana().setEditable(true);
        }
        else{
            getTxtMana().setText("");
            getTxtMana().setEditable(false);
        }
    }//GEN-LAST:event_chkManaActionPerformed

    private void chkSorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSorteActionPerformed
        // TODO add your handling code here:
        if(chkSorte.isSelected()){
            getTxtSorte().setEditable(true);
        }
        else{
            getTxtSorte().setText("");
            getTxtSorte().setEditable(false);
        }
    }//GEN-LAST:event_chkSorteActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JCheckBox chkDestreza;
    private javax.swing.JCheckBox chkFisico;
    private javax.swing.JCheckBox chkInteligencia;
    private javax.swing.JCheckBox chkMana;
    private javax.swing.JCheckBox chkMente;
    private javax.swing.JCheckBox chkPercepcao;
    private javax.swing.JCheckBox chkSorte;
    private javax.swing.JCheckBox chkVontade;
    private javax.swing.ButtonGroup grpTipoEquipamento;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JPanel pnlNovoEquipamento;
    private javax.swing.JRadioButton rdbArma;
    private javax.swing.JRadioButton rdbArmadura;
    private javax.swing.JRadioButton rdbItem;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtDestreza;
    private javax.swing.JTextField txtFisico;
    private javax.swing.JTextField txtInteligencia;
    private javax.swing.JTextField txtMana;
    private javax.swing.JTextField txtMente;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPercepcao;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtSorte;
    private javax.swing.JTextField txtVontade;
    // End of variables declaration//GEN-END:variables


}
