/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package opera.view.PaineisDeCadastro;

import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTextField;
import opera.view.MoldePaineis;

/**
 *
 * @author Luciano
 */
public class PnlCadastrarHabilidade extends MoldePaineis {

    
    
    /**
     * Getters
     */
    public JPanel getPnlNovaHabilidade() {
        return pnlNovaHabilidade;
    }

    public void setPnlNovaHabilidade(JPanel pnlNovaHabilidade) {
        this.pnlNovaHabilidade = pnlNovaHabilidade;
    }
    
    public JButton getBtnCadastrar(){
        return btnCadastrar;
    }
    public JButton getBtnCancelar(){
        return btnCancelar;
    }
    
    public JTextField getTxtCusto(){
        return txtCusto;
    }
    public JTextField getTxtNivel(){
        return txtNivel;
    }
    public JTextField getTxtNome(){
        return txtNome;
    }
    public JTextField getTxtTeste(){
        return txtTeste;
    }

    public void setTxtCusto(int txtCusto) {
        this.txtCusto.setText(""+txtCusto);
    }

    public void setTxtNivel(int txtNivel) {
        this.txtNivel.setText(""+txtNivel);
    }

    public void setTxtNome(String txtNome) {
        this.txtNome.setText(txtNome);
    }

    public void setTxtTeste(int txtTeste) {
        this.txtTeste.setText(""+txtTeste);
    }
    
    
    
    

    /**
     * Creates new form PnlCadastrarHabilidade
     */
    public PnlCadastrarHabilidade() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNovaHabilidade = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblNivel = new javax.swing.JLabel();
        lblTeste = new javax.swing.JLabel();
        lblCusto = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtNivel = new javax.swing.JTextField();
        txtTeste = new javax.swing.JTextField();
        txtCusto = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        pnlNovaHabilidade.setBorder(javax.swing.BorderFactory.createTitledBorder("Nova Habilidade"));

        lblNome.setText("Nome:");
        lblNome.setToolTipText("Digite o nome da Nova Habilidade");

        lblNivel.setText("Nivel:");

        lblTeste.setText("Teste:");

        lblCusto.setText("Custo:");
        lblCusto.setToolTipText("Digite o valor do Custo da Habilidade");

        txtNome.setToolTipText("Digite o nome da Nova Habilidade");
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        txtCusto.setToolTipText("Digite o valor do Custo da Habilidade");

        javax.swing.GroupLayout pnlNovaHabilidadeLayout = new javax.swing.GroupLayout(pnlNovaHabilidade);
        pnlNovaHabilidade.setLayout(pnlNovaHabilidadeLayout);
        pnlNovaHabilidadeLayout.setHorizontalGroup(
            pnlNovaHabilidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNovaHabilidadeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNovaHabilidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNome)
                    .addComponent(lblTeste)
                    .addComponent(lblCusto)
                    .addComponent(lblNivel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlNovaHabilidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNome)
                    .addGroup(pnlNovaHabilidadeLayout.createSequentialGroup()
                        .addGroup(pnlNovaHabilidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNivel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(txtTeste)
                            .addComponent(txtCusto))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlNovaHabilidadeLayout.setVerticalGroup(
            pnlNovaHabilidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNovaHabilidadeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlNovaHabilidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlNovaHabilidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNivel)
                    .addComponent(txtNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlNovaHabilidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTeste)
                    .addComponent(txtTeste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlNovaHabilidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCusto)
                    .addComponent(txtCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlNovaHabilidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 161, Short.MAX_VALUE)
                        .addComponent(btnCadastrar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlNovaHabilidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel lblCusto;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTeste;
    private javax.swing.JPanel pnlNovaHabilidade;
    private javax.swing.JTextField txtCusto;
    private javax.swing.JTextField txtNivel;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTeste;
    // End of variables declaration//GEN-END:variables

}
