/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package opera.view.PaineisDeCadastro;

import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Luciano
 */
public class PnlCadastrarFichaParte02 extends javax.swing.JPanel {
    
    /**
     * Getters
     */
    public JButton getBtnCancelar(){
        return btnCancelar;
    }
    public JButton getBtnCadastrar(){
        return btnCadastrar;
    }
    
    public JTextField getTxtDestreza(){
        return txtDestreza;
    }
    public JTextField getTxtFisico(){
        return txtFisico;
    }
    public JTextField getTxtInteligencia(){
        return txtInteligencia;
    }
    public JTextField getTxtMana(){
        return txtMana;
    }
    public JTextField getTxtMente(){
        return txtMente;
    }
    public JTextField getTxtPercepcao(){
        return txtPercepcao;
    }
    public JTextField getTxtSorte(){
        return txtSorte;
    }
    public JTextField getTxtVontade(){
        return txtVontade;
    }

    public void setTxtDestreza(int txtDestreza) {
        this.txtDestreza.setText(""+txtDestreza);
    }

    public void setTxtFisico(int txtFisico) {
        this.txtFisico.setText(""+txtFisico);
    }

    public void setTxtInteligencia(int txtInteligencia) {
        this.txtInteligencia.setText(""+txtInteligencia);
    }

    public void setTxtMana(int txtMana) {
        this.txtMana.setText(""+txtMana);
    }

    public void setTxtMente(int txtMente) {
        this.txtMente.setText(""+txtMente);
    }

    public void setTxtPercepcao(int txtPercepcao) {
        this.txtPercepcao.setText(""+txtPercepcao);
    }

    public void setTxtSorte(int txtSorte) {
        this.txtSorte.setText(""+txtSorte);
    }

    public void setTxtVontade(int txtVontade) {
        this.txtVontade.setText(""+txtVontade);
    }
    

    /**
     * Creates new form PnlCadastrarFichaParte02
     */
    public PnlCadastrarFichaParte02() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAtributos = new javax.swing.JPanel();
        lblFisico = new javax.swing.JLabel();
        txtFisico = new javax.swing.JTextField();
        lblDestreza = new javax.swing.JLabel();
        txtDestreza = new javax.swing.JTextField();
        lblInteligencia = new javax.swing.JLabel();
        txtInteligencia = new javax.swing.JTextField();
        lblVontade = new javax.swing.JLabel();
        txtVontade = new javax.swing.JTextField();
        txtPercepcao = new javax.swing.JTextField();
        txtMente = new javax.swing.JTextField();
        txtMana = new javax.swing.JTextField();
        txtSorte = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();

        pnlAtributos.setBorder(javax.swing.BorderFactory.createTitledBorder("Atributos"));

        lblFisico.setText("Fisico:");

        lblDestreza.setText("Destreza:");

        lblInteligencia.setText("Inteligencia:");

        txtInteligencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInteligenciaActionPerformed(evt);
            }
        });

        lblVontade.setText("Vontade:");

        txtMente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMenteActionPerformed(evt);
            }
        });

        jLabel1.setText("Percepcao:");

        jLabel2.setText("Mente:");

        jLabel3.setText("Mana:");

        jLabel4.setText("Sorte:");

        javax.swing.GroupLayout pnlAtributosLayout = new javax.swing.GroupLayout(pnlAtributos);
        pnlAtributos.setLayout(pnlAtributosLayout);
        pnlAtributosLayout.setHorizontalGroup(
            pnlAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAtributosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlAtributosLayout.createSequentialGroup()
                        .addComponent(lblDestreza)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDestreza, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAtributosLayout.createSequentialGroup()
                        .addGroup(pnlAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInteligencia)
                            .addComponent(lblFisico))
                        .addGroup(pnlAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlAtributosLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtInteligencia, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAtributosLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlAtributosLayout.createSequentialGroup()
                        .addComponent(lblVontade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtVontade, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(pnlAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPercepcao, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(txtMente)
                    .addComponent(txtMana)
                    .addComponent(txtSorte))
                .addContainerGap())
        );
        pnlAtributosLayout.setVerticalGroup(
            pnlAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAtributosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFisico)
                    .addComponent(txtFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPercepcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDestreza)
                    .addComponent(txtDestreza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInteligencia)
                    .addComponent(txtInteligencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVontade)
                    .addComponent(txtVontade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCancelar.setText("Cancelar");

        btnCadastrar.setText("Cadastrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAtributos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAtributos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnCadastrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtInteligenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInteligenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInteligenciaActionPerformed

    private void txtMenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMenteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblDestreza;
    private javax.swing.JLabel lblFisico;
    private javax.swing.JLabel lblInteligencia;
    private javax.swing.JLabel lblVontade;
    private javax.swing.JPanel pnlAtributos;
    private javax.swing.JTextField txtDestreza;
    private javax.swing.JTextField txtFisico;
    private javax.swing.JTextField txtInteligencia;
    private javax.swing.JTextField txtMana;
    private javax.swing.JTextField txtMente;
    private javax.swing.JTextField txtPercepcao;
    private javax.swing.JTextField txtSorte;
    private javax.swing.JTextField txtVontade;
    // End of variables declaration//GEN-END:variables
    
}
