/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.PaineisDeCadastro;

import exception.JTextFieldInvalidoException;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.Constantes;
import validacao.ValidarCampos;

/**
 *
 * @author Luciano
 */
public class PnlCadastrarFicha extends javax.swing.JPanel {

    /**
     * Creates new form PnlCadastrarFicha
     */
    public PnlCadastrarFicha() {
        initComponents();
        PainelFuncoes.definirCorDaBordaJTextField(this, Color.GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpTipoFicha = new javax.swing.ButtonGroup();
        pnlNome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPersonagem = new javax.swing.JTextField();
        txtJogador = new javax.swing.JTextField();
        pnlTipoFicha = new javax.swing.JPanel();
        rdbJogador = new javax.swing.JRadioButton();
        rdbNpc = new javax.swing.JRadioButton();
        rdbMonstro = new javax.swing.JRadioButton();
        pnlCampanha = new javax.swing.JPanel();
        txtCampanha = new javax.swing.JTextField();
        pnlExperiencia = new javax.swing.JPanel();
        txtExperiencia = new javax.swing.JTextField();
        pnlAtributos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtInteligencia = new javax.swing.JTextField();
        txtDestreza = new javax.swing.JTextField();
        txtFisico = new javax.swing.JTextField();
        txtVontade = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPercepcao = new javax.swing.JTextField();
        txtMente = new javax.swing.JTextField();
        txtMana = new javax.swing.JTextField();
        txtSorte = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();

        pnlNome.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));

        jLabel1.setText("Jogador:");

        jLabel2.setText("Personagem:");

        txtPersonagem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPersonagemFocusLost(evt);
            }
        });

        txtJogador.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtJogadorFocusLost(evt);
            }
        });

        javax.swing.GroupLayout pnlNomeLayout = new javax.swing.GroupLayout(pnlNome);
        pnlNome.setLayout(pnlNomeLayout);
        pnlNomeLayout.setHorizontalGroup(
            pnlNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtJogador)
                    .addComponent(txtPersonagem))
                .addContainerGap())
        );
        pnlNomeLayout.setVerticalGroup(
            pnlNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtJogador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlTipoFicha.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Ficha"));

        grpTipoFicha.add(rdbJogador);
        rdbJogador.setText("Jogador");
        rdbJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbJogadorActionPerformed(evt);
            }
        });

        grpTipoFicha.add(rdbNpc);
        rdbNpc.setText("NPC");
        rdbNpc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbNpcActionPerformed(evt);
            }
        });

        grpTipoFicha.add(rdbMonstro);
        rdbMonstro.setText("Monstro");
        rdbMonstro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbMonstroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTipoFichaLayout = new javax.swing.GroupLayout(pnlTipoFicha);
        pnlTipoFicha.setLayout(pnlTipoFichaLayout);
        pnlTipoFichaLayout.setHorizontalGroup(
            pnlTipoFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTipoFichaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTipoFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbJogador)
                    .addComponent(rdbNpc)
                    .addComponent(rdbMonstro))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTipoFichaLayout.setVerticalGroup(
            pnlTipoFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTipoFichaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdbJogador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbNpc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbMonstro))
        );

        pnlCampanha.setBorder(javax.swing.BorderFactory.createTitledBorder("Campanha"));

        txtCampanha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCampanhaActionPerformed(evt);
            }
        });
        txtCampanha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCampanhaFocusLost(evt);
            }
        });

        javax.swing.GroupLayout pnlCampanhaLayout = new javax.swing.GroupLayout(pnlCampanha);
        pnlCampanha.setLayout(pnlCampanhaLayout);
        pnlCampanhaLayout.setHorizontalGroup(
            pnlCampanhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCampanha)
        );
        pnlCampanhaLayout.setVerticalGroup(
            pnlCampanhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCampanha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlExperiencia.setBorder(javax.swing.BorderFactory.createTitledBorder("Experiencia"));

        txtExperiencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExperienciaActionPerformed(evt);
            }
        });
        txtExperiencia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtExperienciaFocusLost(evt);
            }
        });

        javax.swing.GroupLayout pnlExperienciaLayout = new javax.swing.GroupLayout(pnlExperiencia);
        pnlExperiencia.setLayout(pnlExperienciaLayout);
        pnlExperienciaLayout.setHorizontalGroup(
            pnlExperienciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtExperiencia)
        );
        pnlExperienciaLayout.setVerticalGroup(
            pnlExperienciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlAtributos.setBorder(javax.swing.BorderFactory.createTitledBorder("Atributos"));

        jLabel3.setText("Fisico:");

        jLabel4.setText("Destreza:");

        jLabel5.setText("Inteligencia:");

        jLabel6.setText("Vontade:");

        txtInteligencia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtInteligenciaFocusLost(evt);
            }
        });

        txtDestreza.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDestrezaFocusLost(evt);
            }
        });

        txtFisico.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFisicoFocusLost(evt);
            }
        });

        txtVontade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVontadeFocusLost(evt);
            }
        });

        jLabel7.setText("Percepcao:");

        jLabel8.setText("Mente:");

        jLabel9.setText("Mana:");

        jLabel10.setText("Sorte:");

        txtPercepcao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPercepcaoFocusLost(evt);
            }
        });

        txtMente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMenteFocusLost(evt);
            }
        });

        txtMana.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtManaFocusLost(evt);
            }
        });

        txtSorte.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSorteFocusLost(evt);
            }
        });

        javax.swing.GroupLayout pnlAtributosLayout = new javax.swing.GroupLayout(pnlAtributos);
        pnlAtributos.setLayout(pnlAtributosLayout);
        pnlAtributosLayout.setHorizontalGroup(
            pnlAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAtributosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtVontade, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(txtInteligencia, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDestreza, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtFisico, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(pnlAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(12, 12, 12)
                .addGroup(pnlAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtMana, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(txtMente, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPercepcao, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSorte))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAtributosLayout.setVerticalGroup(
            pnlAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAtributosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtPercepcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDestreza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtMente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtInteligencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtMana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtVontade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtSorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlTipoFicha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlExperiencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlCampanha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(pnlAtributos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlCampanha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlTipoFicha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAtributos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar)
                    .addComponent(btnCadastrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        PainelFuncoes.limparTodosOsCampos(this);
        PainelFuncoes.definirCorDaBordaJTextField(this, Color.GRAY);
        grpTipoFicha.clearSelection();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtJogadorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtJogadorFocusLost
        // TODO add your handling code here:
        try{
            ValidarCampos.validarCampoTexto((JTextField)evt.getSource(), false);
        } catch(JTextFieldInvalidoException e){ 
        }
    }//GEN-LAST:event_txtJogadorFocusLost

    private void txtPersonagemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPersonagemFocusLost
        // TODO add your handling code here:
        try{
            ValidarCampos.validarCampoTexto((JTextField)evt.getSource(), true);
        } catch(JTextFieldInvalidoException e){
        }
    }//GEN-LAST:event_txtPersonagemFocusLost

    private void txtCampanhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCampanhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCampanhaActionPerformed

    private void txtCampanhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCampanhaFocusLost
        // TODO add your handling code here:
        try{
            ValidarCampos.validarCampoTexto((JTextField)evt.getSource(), true);
        } catch(JTextFieldInvalidoException e){
            
        }
    }//GEN-LAST:event_txtCampanhaFocusLost

    private void txtExperienciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExperienciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExperienciaActionPerformed

    private void txtExperienciaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtExperienciaFocusLost
        // TODO add your handling code here:
        try{
            ValidarCampos.validarCampoInteiro((JTextField)evt.getSource());
        } catch(JTextFieldInvalidoException e){
        }
    }//GEN-LAST:event_txtExperienciaFocusLost

    private void txtFisicoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFisicoFocusLost
        // TODO add your handling code here:
        try{
            ValidarCampos.validarCampoInteiro((JTextField)evt.getSource());
        } catch(JTextFieldInvalidoException e){
        }
    }//GEN-LAST:event_txtFisicoFocusLost

    private void txtDestrezaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDestrezaFocusLost
        // TODO add your handling code here:
        try{
            ValidarCampos.validarCampoInteiro((JTextField)evt.getSource());
        } catch(JTextFieldInvalidoException e){
        }
    }//GEN-LAST:event_txtDestrezaFocusLost

    private void txtInteligenciaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInteligenciaFocusLost
        // TODO add your handling code here:
        try{
            ValidarCampos.validarCampoInteiro((JTextField)evt.getSource());
        } catch(JTextFieldInvalidoException e){
        }
    }//GEN-LAST:event_txtInteligenciaFocusLost

    private void txtVontadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVontadeFocusLost
        // TODO add your handling code here:
        try{
            ValidarCampos.validarCampoInteiro((JTextField)evt.getSource());
        } catch(JTextFieldInvalidoException e){
        }
    }//GEN-LAST:event_txtVontadeFocusLost

    private void txtPercepcaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPercepcaoFocusLost
        // TODO add your handling code here:
        try{
            ValidarCampos.validarCampoInteiro((JTextField)evt.getSource());
        } catch(JTextFieldInvalidoException e){
        }
    }//GEN-LAST:event_txtPercepcaoFocusLost

    private void txtMenteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMenteFocusLost
        // TODO add your handling code here:
        try{
            ValidarCampos.validarCampoInteiro((JTextField)evt.getSource());
        } catch(JTextFieldInvalidoException e){
        }
    }//GEN-LAST:event_txtMenteFocusLost

    private void txtManaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtManaFocusLost
        // TODO add your handling code here:
        try{
            ValidarCampos.validarCampoInteiro((JTextField)evt.getSource());
        } catch(JTextFieldInvalidoException e){
        }
    }//GEN-LAST:event_txtManaFocusLost

    private void txtSorteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSorteFocusLost
        // TODO add your handling code here:
        try{
            ValidarCampos.validarCampoInteiro((JTextField)evt.getSource());
        } catch(JTextFieldInvalidoException e){
        }
    }//GEN-LAST:event_txtSorteFocusLost

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        try{
            String jogador = ValidarCampos.validarCampoTexto(txtJogador, false);
            String personagem = ValidarCampos.validarCampoTexto(txtPersonagem, true);
            String campanha = ValidarCampos.validarCampoTexto(txtCampanha, true);
            int experiencia = ValidarCampos.validarCampoInteiro(txtExperiencia);

            int atributo[] = new int[8];
            final int FISICO = Constantes.Atributos.FISICO;
            final int DESTREZA = Constantes.Atributos.DESTREZA;
            final int INTELIGENCIA = Constantes.Atributos.INTELIGENCIA;
            final int VONTADE = Constantes.Atributos.VONTADE;
            final int PERCEPCAO = Constantes.Atributos.PERCEPCAO;
            final int MENTE = Constantes.Atributos.MENTE;
            final int MANA = Constantes.Atributos.MANA;
            final int SORTE = Constantes.Atributos.SORTE;
            atributo[FISICO] = ValidarCampos.validarCampoInteiro(txtFisico);
            atributo[DESTREZA] = ValidarCampos.validarCampoInteiro(txtDestreza);
            atributo[INTELIGENCIA] = ValidarCampos.validarCampoInteiro(txtInteligencia);
            atributo[VONTADE] = ValidarCampos.validarCampoInteiro(txtVontade);
            atributo[PERCEPCAO] = ValidarCampos.validarCampoInteiro(txtPercepcao);
            atributo[MENTE] = ValidarCampos.validarCampoInteiro(txtMente);
            atributo[MANA] = ValidarCampos.validarCampoInteiro(txtMana);
            atributo[SORTE] = ValidarCampos.validarCampoInteiro(txtSorte);

            String tipo = null;
            if(rdbJogador.isSelected()){
                tipo = "Jogador";
            }
            if(rdbNpc.isSelected()){
                tipo = "NPC";
            }
            if(rdbMonstro.isSelected()){
                tipo = "Monstro";
            }

            if(tipo == null){
                rdbJogador.setForeground(Color.RED);
                rdbNpc.setForeground(Color.RED);
                rdbMonstro.setForeground(Color.RED);

                rdbJogador.setToolTipText("Algum dos Tipos de Ficha deve ser Selecionado");
                rdbNpc.setToolTipText("Algum dos Tipos de Ficha deve ser Selecionado");
                rdbMonstro.setToolTipText("Algum dos Tipos de Ficha deve ser Selecionado");
                pnlTipoFicha.setToolTipText("Algum dos Tipos de Ficha deve ser Selecionado");
                
                JOptionPane.showMessageDialog(null,"ERROR: " + "Tipo de Ficha nao Selecionado.","Erro",JOptionPane.ERROR_MESSAGE);
            }else{
                if( (tipo.equals("npc")) || (tipo.equals("monstro")) ){
                    JOptionPane.showMessageDialog(null,"Cadastro Ficha: " + personagem +"\nRealizado com Sucesso!","Concluido",JOptionPane.INFORMATION_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(null,"Cadastro Ficha: " + personagem +"\nRealizado com Sucesso!","Concluido",JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch(JTextFieldInvalidoException e){
            JOptionPane.showMessageDialog(null,"ERROR: " + e.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void rdbJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbJogadorActionPerformed
        // TODO add your handling code here:
        rdbJogador.setForeground(Color.BLACK);
        rdbNpc.setForeground(Color.BLACK);
        rdbMonstro.setForeground(Color.BLACK);
        
        rdbJogador.setToolTipText("");
        rdbNpc.setToolTipText("");
        rdbMonstro.setToolTipText("");
    }//GEN-LAST:event_rdbJogadorActionPerformed

    private void rdbNpcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbNpcActionPerformed
        // TODO add your handling code here:
        rdbJogador.setForeground(Color.BLACK);
        rdbNpc.setForeground(Color.BLACK);
        rdbMonstro.setForeground(Color.BLACK);
        
        rdbJogador.setToolTipText("");
        rdbNpc.setToolTipText("");
        rdbMonstro.setToolTipText("");
    }//GEN-LAST:event_rdbNpcActionPerformed

    private void rdbMonstroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbMonstroActionPerformed
        // TODO add your handling code here:
        rdbJogador.setForeground(Color.BLACK);
        rdbNpc.setForeground(Color.BLACK);
        rdbMonstro.setForeground(Color.BLACK);
        
        rdbJogador.setToolTipText("");
        rdbNpc.setToolTipText("");
        rdbMonstro.setToolTipText("");
    }//GEN-LAST:event_rdbMonstroActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.ButtonGroup grpTipoFicha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pnlAtributos;
    private javax.swing.JPanel pnlCampanha;
    private javax.swing.JPanel pnlExperiencia;
    private javax.swing.JPanel pnlNome;
    private javax.swing.JPanel pnlTipoFicha;
    private javax.swing.JRadioButton rdbJogador;
    private javax.swing.JRadioButton rdbMonstro;
    private javax.swing.JRadioButton rdbNpc;
    private javax.swing.JTextField txtCampanha;
    private javax.swing.JTextField txtDestreza;
    private javax.swing.JTextField txtExperiencia;
    private javax.swing.JTextField txtFisico;
    private javax.swing.JTextField txtInteligencia;
    private javax.swing.JTextField txtJogador;
    private javax.swing.JTextField txtMana;
    private javax.swing.JTextField txtMente;
    private javax.swing.JTextField txtPercepcao;
    private javax.swing.JTextField txtPersonagem;
    private javax.swing.JTextField txtSorte;
    private javax.swing.JTextField txtVontade;
    // End of variables declaration//GEN-END:variables
}
