/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package opera.view.PaineisDeAlteracao;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComboBox;
import opera.model.Caracteristica;
import opera.model.Jogo;
import opera.view.MoldePaineis;
import opera.view.PaineisDeCadastro.PnlCadastrarCaracteristica;

/**
 *
 * @author Luciano
 */
public class PnlAlterarCaracteristica extends MoldePaineis {

    /**
     * Creates new form PnlAlterarCaracteristica
     */
    public PnlAlterarCaracteristica(Jogo jogo) {
        initComponents();
        this.setJogo(jogo);
        pnlCadastrarCaracteristica.getBtnCadastrar().setVisible(false);
        pnlCadastrarCaracteristica.getPnlNovaCaracteristica().setBorder(BorderFactory.createTitledBorder("Caracteristica"));
        this.carregarCmbSelecionar();
        habilitarCampos(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblSelecionar = new javax.swing.JLabel();
        cmbSelecionar = new javax.swing.JComboBox();
        btnAlterar = new javax.swing.JButton();
        pnlCadastrarCaracteristica = new opera.view.PaineisDeCadastro.PnlCadastrarCaracteristica();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecionar Caracteristica"));

        lblSelecionar.setText("Caracteristica:");

        cmbSelecionar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSelecionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbSelecionar, 0, 244, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelecionar)
                    .addComponent(cmbSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAlterar.setText("Alterar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAlterar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pnlCadastrarCaracteristica, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlCadastrarCaracteristica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlterar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JComboBox cmbSelecionar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblSelecionar;
    private opera.view.PaineisDeCadastro.PnlCadastrarCaracteristica pnlCadastrarCaracteristica;
    // End of variables declaration//GEN-END:variables
    private String endereco;
    private Jogo jogo;
    private Caracteristica caracteristica;
    
    public void preencherCampos() throws IOException, ClassNotFoundException{
        String itemSelecionado = (String) cmbSelecionar.getSelectedItem();
        
        String enderecoObjeto = endereco + "\\" + itemSelecionado +".txt";
        
        FileInputStream fis = new FileInputStream(enderecoObjeto);
        try (ObjectInputStream ois = new ObjectInputStream(fis)) {
            caracteristica = (Caracteristica) ois.readObject();
        }
        //  new JTextField()
        pnlCadastrarCaracteristica.getTxtNome().setText(caracteristica.getNome());
        pnlCadastrarCaracteristica.getTxtDescricao().setText(caracteristica.getDescricao());
        pnlCadastrarCaracteristica.getTxtCusto().setText(""+caracteristica.getCusto());
        
        if(caracteristica.getModificador() != null){
            
            if(caracteristica.getModificador()[0] > 0){
                pnlCadastrarCaracteristica.getChkFisico().setSelected(true);
                pnlCadastrarCaracteristica.getTxtFisico().setEditable(true);
                pnlCadastrarCaracteristica.getTxtFisico().setText(""+caracteristica.getModificador()[0]);
            }
            if(caracteristica.getModificador()[1] > 0){
                pnlCadastrarCaracteristica.getChkDestreza().setSelected(true);
                pnlCadastrarCaracteristica.getTxtDestreza().setEditable(true);
                pnlCadastrarCaracteristica.getTxtDestreza().setText(""+caracteristica.getModificador()[1]);
            }
            if(caracteristica.getModificador()[2] > 0){
                pnlCadastrarCaracteristica.getChkInteligencia().setSelected(true);
                pnlCadastrarCaracteristica.getTxtInteligencia().setEditable(true);
                pnlCadastrarCaracteristica.getTxtInteligencia().setText(""+caracteristica.getModificador()[2]);
            }
            if(caracteristica.getModificador()[3] > 0){
                pnlCadastrarCaracteristica.getChkVontade().setSelected(true);
                pnlCadastrarCaracteristica.getTxtVontade().setEditable(true);
                pnlCadastrarCaracteristica.getTxtVontade().setText(""+caracteristica.getModificador()[3]);
            }
            if(caracteristica.getModificador()[4] > 0){
                pnlCadastrarCaracteristica.getChkPercepcao().setSelected(true);
                pnlCadastrarCaracteristica.getTxtPercepcao().setEditable(true);
                pnlCadastrarCaracteristica.getTxtPercepcao().setText(""+caracteristica.getModificador()[4]);
            }
            if(caracteristica.getModificador()[5] > 0){
                pnlCadastrarCaracteristica.getChkMana().setSelected(true);
                pnlCadastrarCaracteristica.getTxtMana().setEditable(true);
                pnlCadastrarCaracteristica.getTxtMana().setText(""+caracteristica.getModificador()[5]);
            }
            if(caracteristica.getModificador()[6] > 0){
                pnlCadastrarCaracteristica.getChkMente().setSelected(true);
                pnlCadastrarCaracteristica.getTxtMente().setEditable(true);
                pnlCadastrarCaracteristica.getTxtMente().setText(""+caracteristica.getModificador()[6]);
            }
            if(caracteristica.getModificador()[7] > 0){
                pnlCadastrarCaracteristica.getChkSorte().setSelected(true);
                pnlCadastrarCaracteristica.getTxtSorte().setEditable(true);
                pnlCadastrarCaracteristica.getTxtSorte().setText(""+caracteristica.getModificador()[7]);
            }
            
        }
        
    }
    
    @Override
    public void atualizarJComboBox(){
        carregarCmbSelecionar();
    }
    
    private void carregarCmbSelecionar(){
        cmbSelecionar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ""}));
        
        File diretorio;
        diretorio = new File("C:\\Opera\\Jogos\\" + jogo.getNome() + "\\Caracteristicas");
        
        endereco = diretorio.getAbsolutePath();
        
        if(diretorio.exists()){
            //statusDiretorio = diretorio.mkdir();
            String diretorios[] = diretorio.list();
            for(int i = 0; i < diretorios.length; i++){
                //System.out.println(diretorios[i]);
                String item = diretorios[i].substring(0, (diretorios[i].length()-4) );
                cmbSelecionar.addItem(item);
            }
        }
    }

    public final void habilitarCampos(boolean habilitar){
        pnlCadastrarCaracteristica.getTxtNome().setEditable(habilitar);
        pnlCadastrarCaracteristica.getTxtDescricao().setEditable(habilitar);
        pnlCadastrarCaracteristica.getTxtCusto().setEditable(habilitar);

        pnlCadastrarCaracteristica.getChkFisico().setEnabled(habilitar);
        pnlCadastrarCaracteristica.getChkDestreza().setEnabled(habilitar);
        pnlCadastrarCaracteristica.getChkInteligencia().setEnabled(habilitar);
        pnlCadastrarCaracteristica.getChkVontade().setEnabled(habilitar);
        pnlCadastrarCaracteristica.getChkPercepcao().setEnabled(habilitar);
        pnlCadastrarCaracteristica.getChkMana().setEnabled(habilitar);
        pnlCadastrarCaracteristica.getChkMente().setEnabled(habilitar);
        pnlCadastrarCaracteristica.getChkSorte().setEnabled(habilitar);
    }
    
    
    public JButton getBtnAlterar() {
        return btnAlterar;
    }

    public void setBtnAlterar(JButton btnAlterar) {
        this.btnAlterar = btnAlterar;
    }

    public JComboBox getCmbSelecionar() {
        return cmbSelecionar;
    }

    public void setCmbSelecionar(JComboBox cmbSelecionar) {
        this.cmbSelecionar = cmbSelecionar;
    }

    public PnlCadastrarCaracteristica getPnlCadastrarCaracteristica() {
        return pnlCadastrarCaracteristica;
    }

    public void setPnlCadastrarCaracteristica(PnlCadastrarCaracteristica pnlCadastrarCaracteristica1) {
        this.pnlCadastrarCaracteristica = pnlCadastrarCaracteristica1;
    }

    public Jogo getJogo() {
        return jogo;
    }

    public final void setJogo(Jogo jogo) {
        this.jogo = jogo;
    }

    public Caracteristica getCaracteristica() {
        return caracteristica;
    }

    public void setCaracteristica(Caracteristica caracteristica) {
        this.caracteristica = caracteristica;
    }

    
    

}
